server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
